Update BUILDING-OPENSUSE.md
occ-ai/obs-backgroundremoval pull request #474
Opened 2023-10-14 16:19 UTC by saif-ellafi

Build from source in OpenSUSE Tumbleweed - tested

Best regards!

2023-10-14 22:40 UTC, umireon requested changes

2023-10-14 22:40 UTC, umireon commented on docs/BUILDING-OPENSUSE.md
> +.github/scripts/build-linux --skip-deps
```suggestion
cmake . -B build_x86_64 \
  -DCMAKE_C_COMPILER=gcc-12 \
  -DCMAKE_CXX_COMPILER=g++-12 \
  -DQT_VERSION=6 \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DENABLE_FRONTEND_API=ON \
  -DENABLE_QT=ON
```

Can you test this?

2023-10-14 22:41 UTC, umireon commented
Can you remove 

```
sudo zypper install zsh cmake Mesa-libGL-devel \
  ffmpeg-6-libavcodes-devel ffmpeg-6-libavdevice-devel ffmpeg-6-libavformat-devel \
  ffmpeg-6-libavcodec-devel ffmpeg-6-libavdevice-devel ffmpeg-6-libavformat-devel \
  libcurl-devel Mesa-libEGL-devel \
  libpulse-devel libxkbcommon-devel
```

2023-10-18 15:26 UTC, umireon commented
@saif-ellafi Hello can you update the branch as I requested?

2023-10-18 21:24 UTC, saif-ellafi commented
Very sorry @umireon - I moved out of opensuse, can't test. But I can say for sure the script as committed worked fine (CPU only)

2023-10-18 22:32 UTC, saif-ellafi commented
@umireon - will test soon and come back to you

2023-10-18 23:38 UTC, saif-ellafi commented
@umireon - doesn't work

```
saif@saif-ms7c76:~/Repos/obs-backgroundremoval> cmake . -B build_x86_64   -DCMAKE_C_COMPILER=gcc-12   -DCMAKE_CXX_COMPILER=g++-12   -DQT_VERSION=6   -DCMAKE_BUILD_TYPE=RelWithDebInfo   -DCMAKE_POSITION_INDEPENDENT_CODE=ON   -DENABLE_FRONTEND_API=ON   -DENABLE_QT=ON
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_C_COMPILER:

    gcc-12

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_CXX_COMPILER:

    g++-12

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

2023-10-18 23:41 UTC, saif-ellafi commented
Bumped to g++ 13 but now getting

```
CMake Error at CMakeLists.txt:14 (add_library):
  The install of the obs-backgroundremoval target requires changing an RPATH
  from the build tree, but this is not supported with the Ninja generator
  unless on an ELF-based or XCOFF-based platform.  The
  CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set to avoid this relinking
  step.
```

2023-10-18 23:42 UTC, umireon requested changes

2023-10-18 23:42 UTC, umireon commented on docs/BUILDING-OPENSUSE.md
> +sudo zypper in cmake gcc-c++ ninja obs-studio-devel opencv-devel qt6-base-devel zsh curl-devel jq
```suggestion
sudo zypper in cmake gcc12-c++ ninja obs-studio-devel opencv-devel qt6-base-devel zsh curl-devel jq
```

2023-10-18 23:43 UTC, umireon commented
Please use gcc12 not gcc13 as gcc13 is not avaible on Leap

2023-10-18 23:44 UTC, umireon commented
You should not use .github/scripts/build-linux.zsh

2023-10-18 23:45 UTC, umireon commented
You have to remove build_x86_64 directory before running cmake command

2023-10-18 23:45 UTC, umireon requested changes

2023-10-18 23:45 UTC, umireon commented on docs/BUILDING-OPENSUSE.md
> +  -DCMAKE_CXX_COMPILER=g++-13 \
```suggestion
  -DCMAKE_C_COMPILER=gcc-12 \
  -DCMAKE_CXX_COMPILER=g++-12 \
```

2023-10-18 23:49 UTC, saif-ellafi commented
Okay cmake works but the install is failing

```
sudo cmake --install build_x86_64 --prefix /usr
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/lib64/obs-plugins/obs-backgroundremoval/libonnxruntime.so.1.16.0
-- Installing: /usr/lib64/obs-plugins/obs-backgroundremoval/libonnxruntime_providers_shared.so
-- Installing: /usr/lib64/obs-plugins/obs-backgroundremoval/libonnxruntime_providers_cuda.so
-- Installing: /usr/lib64/obs-plugins/obs-backgroundremoval/libonnxruntime_providers_tensorrt.so
CMake Error at build_x86_64/cmake_install.cmake:66 (file):
  file INSTALL cannot find
  "/home/saif/Repos/obs-backgroundremoval/build_x86_64/obs-backgroundremoval.so":
  No such file or directory.
```

2023-10-18 23:51 UTC, umireon requested changes

2023-10-18 23:51 UTC, umireon commented on docs/BUILDING-OPENSUSE.md
> +  -DENABLE_QT=ON
```suggestion
  -DENABLE_QT=ON
cmake --build build_x86_64
```

2023-10-18 23:51 UTC, umireon commented
Run cmake --build build_x86_64 before installing.

2023-10-18 23:57 UTC, saif-ellafi commented
@umireon - thanks. Now it seems to build and install properly. CPU only. Will check now to install cuda and the other mambo-jumbo for GPU support

2023-10-18 23:58 UTC, umireon approved these changes
LGTM

2023-11-30 14:40 UTC, merged