Add GitHub Action to Update the Windows installer to Winget
occ-ai/obs-backgroundremoval pull request #500
Opened 2023-12-20 10:33 UTC by MrHinsh

This should only be merged once https://github.com/microsoft/winget-pkgs/pull/131370 has been approved and it will update this package based on each GitHub Release.

2023-12-20 12:54 UTC, MrHinsh commented
Blocked due to https://github.com/occ-ai/obs-backgroundremoval/issues/499

2024-01-08 15:00 UTC, MrHinsh commented
This is now open on https://github.com/microsoft/winget-pkgs/pull/131370 but has a "no-executable" block. I have commented and hopefully we can get it past the reviewer.

2024-01-09 08:54 UTC, MrHinsh commented
All approved!

![image](https://github.com/occ-ai/obs-backgroundremoval/assets/5205575/5f92730d-d538-4139-86a3-1eca05e067ee)

One can now install this tool using "winget install RoyShilkrot.obs-backgroundremoval"...

This PR adds an Action that triggers whenever there is a release and updates winget with the latest version.

2024-01-10 03:45 UTC, royshil requested changes
we can certainly add this
and thank you very much for the contribution

i have a couple questions

2024-01-10 03:45 UTC, royshil commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
is this `secrets.UPDATETHIS_PAT` needed somewhere?

2024-01-10 03:45 UTC, royshil commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
nit: add newline

2024-01-10 03:45 UTC, royshil commented on .github/actions/winget-update/action.yaml
> +  winget:
so when would this action run? after a release is made?

right now it's not part of any workflow...

2024-01-10 09:13 UTC, MrHinsh commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
Yes, I can change it to the same that you want, but it should be a build variable with a PAT token that has "public_repo" permission

2024-01-10 09:14 UTC, MrHinsh commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
I dont understand this one.

2024-01-10 09:15 UTC, MrHinsh commented on .github/actions/winget-update/action.yaml
> +  winget:
```
on:
  release:
    types: [published]
```

It rund when you crate a published release.

2024-01-10 15:56 UTC, royshil commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
just add a newline `\n` in the end of the file...

2024-01-10 15:58 UTC, royshil commented on .github/actions/winget-update/action.yaml
> +  winget:
in our workflow we only create a draft release and i manually publish it after making notes etc.
is that going to trigger this action? (when i manually publish)

2024-01-10 15:59 UTC, royshil commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
can you explain the PAT token? is this something that Winget expects? i would need to sign up somewhere to get it?

i can add it as a repo secret

2024-01-10 16:42 UTC, MrHinsh commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
Its a GitHub PAT token. Winget-Create creates a Pull Request on Github for the submission. 


Yes, you would create a

2024-01-10 16:44 UTC, MrHinsh commented on .github/actions/winget-update/action.yaml
> +  winget:
Yes it will trigger when its published manually.

2024-01-10 16:55 UTC, umireon commented on .github/actions/winget-update/action.yaml
> +
```suggestion

```

2024-01-10 17:48 UTC, umireon requested changes
Can you fix this file path? I don't think your file will work because this is placed under the wrong path.

2024-01-10 17:51 UTC, MrHinsh commented
@umireon, what path would you like the file under? I used the same format as your existing actions.

2024-01-10 17:53 UTC, MrHinsh commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
@royshil do you have a variable name for your secret that I can use?

2024-01-10 17:55 UTC, umireon commented
The `.github/actions` directory is for hosting custom actions. What you wrote is not a custom action but a workflow. Any workflow files must be stored under the `.github/workflows` directory.

2024-01-10 19:44 UTC, royshil commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
i don't have a PAT yet
what sort of permissions does the PAT need though?
i can create one and add it as a secret

2024-01-10 19:51 UTC, MrHinsh commented
@umireon DONE

2024-01-10 19:51 UTC, MrHinsh commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
It only needs  "public_repo"

2024-01-10 19:52 UTC, MrHinsh commented on .github/actions/winget-update/action.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
https://github.com/microsoft/winget-create/tree/main?tab=readme-ov-file#github-personal-access-token-classic-permissions

2024-01-11 07:44 UTC, umireon requested changes

2024-01-11 07:44 UTC, umireon commented on .github/workflows/winget-update.yaml
> +    types: [published]
```suggestion
    types:
      - published
```

2024-01-11 07:44 UTC, umireon commented on .github/workflows/winget-update.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
```suggestion
          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t '${{ secrets.GITHUB_PUBLIC_REPO_PAT }}'

```

2024-01-11 07:45 UTC, umireon commented on .github/workflows/winget-update.yaml
> +    types: [published]
I prefer this array notation.

2024-01-11 07:45 UTC, umireon commented on .github/workflows/winget-update.yaml
> +          .\wingetcreate.exe update RoyShilkrot.obs-backgroundremoval -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.UPDATETHIS_PAT }}
Give the secret a concise name.

2024-01-11 07:48 UTC, umireon commented
@MrHinsh Who should be the owner of the PAT that this workflow requires? Our organization (occ-ai) or a personal account (@royshil 's one)?

2024-01-11 07:51 UTC, umireon commented
I don't think that the organization PAT can create PR.

2024-01-11 08:32 UTC, MrHinsh commented
I use a non-expiring personal token.

2024-01-18 03:47 UTC, umireon commented
@royshil ping

2024-01-18 20:52 UTC, royshil commented
i cretaed a PAT and added it as a secret
had to change the name since secrets cannot start with `GITHUB_`

2024-01-18 20:54 UTC, royshil commented
how do we test if this works without having to publish a release?

2024-01-18 22:50 UTC, MrHinsh commented
You can't.

2024-01-19 15:32 UTC, royshil commented
ok well this is all set on the repo secrets side
so i suppose we can merge and see if it works in the next version release

2024-01-19 15:32 UTC, royshil approved these changes
i'm ok with landing this

2024-01-21 01:50 UTC, umireon approved these changes
lgtm

2024-01-21 01:50 UTC, merged